### ISSUE TITLE
asset fixes

### ISSUE THREAD

**Issue by craigh** [zikula-modules/Multisites#27]
replace anything starting with `web/` e.g.

`{{ pageAddAsset('stylesheet', 'web/bootstrap/css/bootstrap.min.css') }}`

with

`{{ pageAddAsset('stylesheet', asset('bootstrap/css/bootstrap.min.css')) }}`

replace

`{{ pageAddAsset('javascript', 'jquery') }}`

with

null - jQuery is added always

This doesn't work, I think.

`{{ pageAddAsset('javascript', 'zikula') }}`

the new system has no provision for 'aliases' like the old did.

at present I do not have a good solution.

I'm not sure JS get text ever worked properly anyway

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-modules/Multisites/commit/505538f0a0f123e4d46c172e90511f8934ad56fd and https://github.com/Guite/MostGenerator/commit/a59d6b8aed7d76cb64db2d456b6faf22046ce560

The last one (`zikula`) will be fixed as soon as https://github.com/zikula/core/issues/2601 has been done - see also https://github.com/Guite/MostGenerator/blob/a59d6b8aed7d76cb64db2d456b6faf22046ce560/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/view/Layout.xtend#L87
